M48
; DRILL file {KiCad 8.0.1} date 2024-04-14T22:29:57+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-14T22:29:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.4685Y-3.2087
X4.4685Y-4.7047
T2
X7.4244Y-3.475
X7.4244Y-3.925
M30
